# Generated by Django 3.2.5 on 2021-07-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
